version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '8090:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bookstore
    networks:
      - private_network
    volumes:
      - bookstore_pg_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 10s

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "rodrigues.fricardo@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - private_network

  bookstore:
    container_name: bookstore
    build: .
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookstore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - private_network

volumes:
  bookstore_pg_data:

networks:
  private_network:
    driver: bridge
